### ISSUE TITLE
imap crashes with signal 11 if rados connect fails

### ISSUE THREAD

**Issue by peter-mauritius** [ceph-dovecot/dovecot-ceph-plugin#106]
Nov 10 17:19:31 imap(520000059158-0001): Debug: oid: da13353992d1055ac33200005b78498d, save_date: Thu Jan  1 00:59:59 1970
Nov 10 17:19:31 imap(520000059158-0001): Debug: [START] rbox-save.cpp: rbox_save_mail_write_metadata at line 241
Nov 10 17:19:31 imap(520000059158-0001): Debug: ctx->input->v_offset != output_msg_size 165067 vs 165067
Nov 10 17:19:31 imap(520000059158-0001): Debug: save_date Thu Jan  1 00:59:59 1970
Nov 10 17:19:31 imap(520000059158-0001): Debug: [END] rbox-save.cpp: rbox_save_mail_write_metadata at line 313
Nov 10 17:19:31 imap(520000059158-0001): Debug: ERROR, cannot open rados connection (rbox_save_finish)
Nov 10 17:19:31 imap(520000059158-0001): Debug: [END] rbox-save.cpp: rbox_save_finish at line 431
Nov 10 17:19:31 imap(520000059158-0001): Debug: [START] rbox-save.cpp: rbox_transaction_save_rollback at line 541
Nov 10 17:19:31 imap(520000059158-0001): Fatal: master: service(imap): child 12995 killed with signal 11 (core dumped)

**Comment by jrse** [comment]
ready for retest

**Comment by jrse** [comment]
ready for retest
