### ISSUE TITLE
Quota reached -> exception 

### ISSUE THREAD

**Issue by jrse** [ceph-dovecot/dovecot-ceph-plugin#110]
if quota is reached, dovecote-ceph-plugin fails with Signal 6.

Reproduce:

edit 90-quota.conf
set:   quota_rule = *:storage=1M

store email with attachment > 1M

please find the logfile attached
[dovecot.log.1.gz](https://github.com/ceph-dovecot/dovecot-ceph-plugin/files/1481868/dovecot.log.1.gz)

**Comment by pburow** [comment]
Fixed.
