### ISSUE TITLE
doveadm rbox check -u user

### ISSUE THREAD

**Issue by peter-mauritius** [ceph-dovecot/dovecot-ceph-plugin#113]
Create an doveadm plugin for rbox. 

The first subcommand to implement is "check".  "check" performs a consistency check between the users mailboxes and the objects in the corresponding RADOS namespace. Mail objects that are not referenced by Dovecot's index will be deleted.

**Comment by jrse** [comment]
cleaning up all objects in the users namespace which are not referenced in the index files, 
can be done with:

 doveadm rmb check indices -u <user>  delete_not_referenced_objects

there will be no confirmation!
