### ISSUE TITLE
Unable to find the jansson headers

### ISSUE THREAD

**Issue by alexzh16** [ceph-dovecot/dovecot-ceph-plugin#114]
Hi,

Centos 7 64bit, fresh install os. 
Package jansson-2.10-1.el7.x86_64 already installed and latest version
Package jansson-devel-2.10-1.el7.x86_64 already installed and latest version

bash configure
...
checking for library containing strerror... none required
checking for inline... inline
checking for "dovecot-config"... /usr/lib64/dovecot/dovecot-config
checking whether OS supports plugin dependencies... yes
checking for valgrind... no
checking jansson.h usability... no
checking jansson.h presence... yes
configure: WARNING: jansson.h: present but cannot be compiled
configure: WARNING: jansson.h:     check for missing prerequisite headers?
configure: WARNING: jansson.h: see the Autoconf documentation
configure: WARNING: jansson.h:     section "Present But Cannot Be Compiled"
configure: WARNING: jansson.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/ceph-dovecot/dovecot-ceph-plugin/issues/new ##
configure: WARNING:     ## ----------------------------------------------------------------------------- ##
checking for jansson.h... no
configure: error: Unable to find the jansson headers

**Comment by alexzh16** [comment]
UPD> autoconf (GNU Autoconf) 2.69

**Comment by alexzh16** [comment]
Fix this error: 
in os must be install packet: 
yum install redhat-rpm-config 
issue this. Please add to readme or check script.
thx

**Comment by peter-mauritius** [comment]
Hi,

I am currently on vacation but I will look at the spec file next week. Thanks for your issue.

Peter

**Comment by jrse** [comment]
To build the plugin on centOS 7 minimal you need to have all recommend development tools installed. 
the easiest way is to use 
yum group installl "Development Tools" additionally to the jansson package.

However there is the other thing that centos 7 comes with librados-devel package version 0.94.5 which is pretty old and not supported by our plugin. So you need to find a librados-devel package in a newer version or build ceph by your own, which is straight forward but takes some time. Have a look at http://docs.ceph.com/docs/master/install/build-ceph/ for ceph build instructions. Keep in mind that centos 7 gcc version 4.8.5 is pretty old, so http://docs.ceph.com/docs/master/dev/cxx/ may be of interrest.
