### ISSUE TITLE
testing with one mailbox

### ISSUE THREAD

**Issue by f1-outsourcing** [ceph-dovecot/dovecot-ceph-plugin#115]
I wondered if it is possible to create just some test account that is only using the ceph backend, in a production server. (Sort of to skip creating a test environment)

**Comment by peter-mauritius** [comment]
The storage module to use is determined by the option [mail_location](https://wiki.dovecot.org/MailLocation). This option can be overridden by the [userdb](https://wiki.dovecot.org/UserDatabase) field  mail_location on a per user basis. So, it depends on the capabilities of your userdb.
