### ISSUE TITLE
backup mdbox  -> rbox

### ISSUE THREAD

**Issue by jrse** [ceph-dovecot/dovecot-ceph-plugin#118]
[t10.mdbox.log](https://github.com/ceph-dovecot/dovecot-ceph-plugin/files/1651392/t10.mdbox.log)
[t10.rbox.log](https://github.com/ceph-dovecot/dovecot-ceph-plugin/files/1651393/t10.rbox.log)
[diff.log](https://github.com/ceph-dovecot/dovecot-ceph-plugin/files/1651396/diff.log)

in some cases there is a difference of the keyword order:
e.g.
rbox: $label1 $label4 $label5
mdbox: $label4 $label1 $label5

to reproduce: 
- create mdbox mailbox with imaptest
- do doveadm backup to rbox

validate:

# compare.sh ##################

# users t1 - t100

#!/bin/bash
for i in `seq 1 100`;
do
doveadm fetch -u t$i "guid date.received date.sent flags pop3.uidl seq size.virtual uid user mailbox-guid mailbox" ALL > diff.text1
doveadm -c path to mdbox dovecot.conf fetch -u t$i "guid date.received date.sent flags pop3.uidl seq size.virtual uid user mailbox-guid mailbox" ALL > diff.text2

result=$(diff -y -W 200 diff.text1 diff.text2)

if [ $? -eq 0 ]
then
   echo "all the same t$i"
else
  echo "files are different t$i"
  echo "$result"
fi
done

echo "done"

#################

**Comment by jrse** [comment]
a retest with a backup from mdbox to sdbox shows that the keyword oder is also not preserved.

**Comment by jrse** [comment]
Due to the fact that sdbox storage plugin is handling keywords in the same way, i looked for answers regarding this issue and got the answer:
---
there is nothing that guarantees their ordering
iow, you should not expect that to be preserved
---
So i think we need to modify our check scripts to handle this "random" ordering of keywords.

**Comment by pburow** [comment]
I changed the keyword checking script by omitting the field "flags" now. But I extended the script with manual flags verification.
