### ISSUE TITLE
DB for metadata instead CephFS?

### ISSUE THREAD

**Issue by pkalemba** [ceph-dovecot/dovecot-ceph-plugin#125]
Hi!
Did you consider keeping all metadata in some DB(scylla,cassanda,couchdb)?

**Comment by peter-mauritius** [comment]
Hi!

At the moment, our goal is to store the emails in RADOS objects, as these are the largest contributors to storage usage. In the long term, we also want to eliminate the need to use CephFS or any other shared file system for metadata storage. Using one of these databases is one of the possible options. I would prefer to find a pure RADOS based solution. For now, however, we want to get the hybrid solution ready for production and use it in a larger installation.
