### ISSUE TITLE
iredmail 0.98 (Dovecot 2.2.33) on Ubuntu 18.04 LTS - diverse problems

### ISSUE THREAD

**Issue by thomasklosinsky** [ceph-dovecot/dovecot-ceph-plugin#210]
**Describe the bug**
checking for inline... inline
checking for "dovecot-config"... /usr/lib/dovecot/dovecot-config
checking whether OS supports plugin dependencies... yes
checking for valgrind... no
./configure: line 21506: syntax error near unexpected token \`JANSSON,'
./configure: line 21506: `PKG_CHECK_MODULES(JANSSON, jansson)'

libjansson-dev/bionic,now 2.11-1 amd64  [installiert]
libjansson-doc/bionic 2.11-1 all
libjansson4/bionic,now 2.11-1 amd64  [installiert]
librados-dev/stable,now 13.2.2-1bionic amd64  [installiert]
librados2/stable,now 13.2.2-1bionic amd64  [Installiert,automatisch]
librados2-dbg/stable 13.2.2-1bionic amd64
libradosstriper-dev/stable 13.2.2-1bionic amd64
libradosstriper1/stable,now 13.2.2-1bionic amd64  [Installiert,automatisch]
libradosstriper1-dbg/stable 13.2.2-1bionic amd64

**To Reproduce**
Install Ubuntu 18.04
Install Dovecot
Install dependencies of this plugin
start autogen.sh and configure

**Expected behavior**
configure script should find jansson library installed

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - Ceph Version Mimic 13.2.2
 - Dovecot Version 2.2.33.2

**Comment by thomasklosinsky** [comment]
And when I uncomment the package check in the configuration and give make a chance:

../../../../src/librmb/.libs/librmb.so: undefined reference to `json_dumps'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object_iter_next'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object_iter_value'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object_iter'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object_iter_key'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_delete'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_string'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_loads'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_string_value'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object_set_new'
../../../../src/librmb/.libs/librmb.so: undefined reference to `json_object_get'
collect2: error: ld returned 1 exit status
Makefile:569: recipe for target 'rmb' failed
make[5]: *** [rmb] Error 1
make[5]: Leaving directory '/root/dovecot-ceph-plugin/src/librmb/tools/rmb'
Makefile:471: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/root/dovecot-ceph-plugin/src/librmb/tools'
Makefile:712: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/root/dovecot-ceph-plugin/src/librmb'
Makefile:479: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/dovecot-ceph-plugin/src'
Makefile:532: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/dovecot-ceph-plugin'
Makefile:464: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jrse** [comment]
is pkg-config installed?

**Comment by thomasklosinsky** [comment]
Yes, it is:

 pkg-config --libs jansson
-ljansson

Trying to install with your hint. Will let you know!
Thanks for great support!

**Comment by thomasklosinsky** [comment]
ok. with only dovecot installed it works...
trying a new VM with iredmail and no further configurations

**Comment by thomasklosinsky** [comment]
so...
new VM set up with iredmail 0.9.8 and Dovecot 2.2.33

configure works when copying /etc/dovecot/dovecot.conf to /etc/dovecot/dovecot-config as requested by configure script.

on make this error occured:
In file included from libdict-rados-plugin.c:12:0:
dovecot-dict.h:23:10: fatal error: lib.h: No such file or directory
 #include "lib.h"
          ^~~~~~~
compilation terminated.
Makefile:589: recipe for target 'libdict-rados-plugin.lo' failed
make[3]: *** [libdict-rados-plugin.lo] Error 1
make[3]: Leaving directory '/usr/local/dovecot-ceph-plugin/src/dict-rados'
Makefile:482: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/dovecot-ceph-plugin/src'
Makefile:535: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/dovecot-ceph-plugin'
Makefile:467: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas?

**Comment by thomasklosinsky** [comment]
It works when changing oldincludedir=/usr/include to /usr/include/dovecot in Makefile

Further tests will be made!
