### ISSUE TITLE
doveadm 

### ISSUE THREAD

**Issue by byphone** [ceph-dovecot/dovecot-ceph-plugin#270]
Hello

Try to setup the plugin. All is compiled and setup as the wiki.
i can't access to the doveadm rmb command

How to add the plugin in dovecot conf file ?

Regards

**Comment by jrse** [comment]
rmb is currently not a doveadm plugin, its a separate binary which can be executed independently from doveadm. It should be installed in the same directory as doveadm. Have a look at https://github.com/ceph-dovecot/dovecot-ceph-plugin/tree/master/src/librmb/tools/rmb

**Comment by byphone** [comment]
Thanks a lot for your answer, I'm slowly advancing in the implementation of the plugin with the latest version of CEPH (octopus), do you have an idea of the release date? I use the plugin as part of a voicemail project for an operator

**Comment by jrse** [comment]
can't say for sure, because currently it is under intense test and we are waiting for those results.

**Comment by discostur** [comment]
@jrse can you say anything about the future of the plugin? We are planning a new mail product and would love to use the ceph-dovecot plugin ... is it still under active development? When are you planning to release a new stable version?

Thanks ;)

**Comment by jrse** [comment]
@discostur new stable version is 1.0.0  which running stable in production
