### ISSUE TITLE
build RPM package for SUSE

### ISSUE THREAD

**Issue by peter-mauritius** [ceph-dovecot/dovecot-ceph-plugin#58]
create a spec file for the plugins for SUSE SLES11/12
use the SUSE packages librados-devel and dovecot22-devel

**Comment by dalgaaf** [comment]
First package in OBS for SLES12-SP3, openSUSE Leap 42.3 and Tumbleweed: https://build.opensuse.org/package/show/home:dalgaaf:dovecot-ceph-plugin/dovecot-ceph-plugin 

Still missing header files for librmb in the devel package, they are not installed via "make install" currently. Also a librmb.pc file and some kind of documentation (man page, ...) would be nice.
